language: cpp
dist: bionic
addons:
  apt:
    update: false
    packages:
    - libboost-test-dev
    - libgtest-dev

before_script:
- conan profile update settings.compiler.libcxx=libstdc++11 default

script:
- set -e
- conan install -s build_type=Release --build missing .
- cmake --DCMAKE_BUILD_TYPE=Release . # TODO Use var for type.
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package

deploy:
  provider: bintray
  file: bintray.json
  user: bergentroll
  cleanup: false
  edge: true
