language: cpp
dist: bionic
addons:
  apt:
    update: false
    packages:
    - python3-pip
    - python3-setuptools
    - python3-wheel

install:
  - pip3 install conan==1.24
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default

script:
- set -e
- conan install -s build_type=Release --build missing .
- cmake --DCMAKE_BUILD_TYPE=Release . # TODO Use var for type.
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package

deploy:
  provider: bintray
  file: bintray.json
  user: bergentroll
  cleanup: false
  edge: true
